version: "3"
services:
  go:
    container_name: go
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - type: bind
        source: "./backend"
        target: "/go/src/app"
    working_dir: /go/src/app
    networks:
      - default
      - golang_network
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./database/Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./database/.env
    volumes:
      - type: volume
        source: mysql_test_volume
        target: /var/lib/mysql
      - type: bind
        source: ./database/init
        target: /docker-entrypoint-initdb.d
    networks:
      - default
      - golang_network

volumes:
  mysql_test_volume:
    name: mysql_test_volume

networks:
  golang_network:
    external: true