version: "3"
services:
  go:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: "./backend"
        target: "/go/src/app"
    working_dir: /go/src/app